search_keywords:
  - "Tesla"
  - "Nvidia"
  - "Artificial Intelligence"
  - "Federal Reserve"

settings:
  language: "en"
  page_size: 50
  sort_by: "publishedAt"


# Cloud Storage Settings
s3:
  bucket_name: "YOUR_BUCKET_NAME"

api:
  key : "YOUR_API_KEY"